export const getRandomPrompt = (currentPrompt) => {
  const prompts = [
    'An Armchair In The Shape Of An Avocado',
    'A Surrealist Dream-Like Oil Painting By Salvador Dalí Of A Cat Playing Checkers',
    'Teddy Bears Shopping For Groceries In Japan, Ukiyo-E',
    'An Oil Painting By Matisse Of A Humanoid Robot Playing Chess',
    'Panda Mad Scientist Mixing Sparkling Chemicals, Digital Art',
    "A Macro 35mm Photograph Of Two Mice In Hawaii, They're Each Wearing Tiny Swimsuits And Are Carrying Tiny Surf Boards, Digital Art",
    '3D Render Of A Cute Tropical Fish In An Aquarium On A Dark Blue Background, Digital Art',
    'An Astronaut Lounging In A Tropical Resort In Space, Vaporwave',
    'An Oil Painting Portrait Of A Capybara Wearing Medieval Royal Robes And An Ornate Crown On A Dark Background',
    'A Stained Glass Window Depicting A Hamburger And French Fries',
    'A Pencil And Watercolor Drawing Of A Bright City In The Future With Flying Cars',
    'A Sunlit Indoor Lounge Area With A Pool With Clear Water And Another Pool With Translucent Pastel Pink Water, Next To A Big Window, Digital Art',
    'A Fortune-Telling Shiba Inu Reading Your Fate In A Giant Hamburger, Digital Art',
    'A Sea Otter With A Pearl Earring By Johannes Vermeer',
    'An Oil Pastel Drawing Of An Annoyed Cat In A Spaceship',
    'A Painting Of A Fox In The Style Of Starry Night',
    'A Bowl Of Soup That Looks Like A Monster, Knitted Out Of Wool',
    'A Plush Toy Robot Sitting Against A Yellow Wall',
    'A Synthwave Style Sunset Above The Reflecting Water Of The Sea, Digital Art',
    'Two Futuristic Towers With A Skybridge Covered In Lush Foliage, Digital Art',
    'A 3D Render Of A Rainbow Colored Hot Air Balloon Flying Above A Reflective Lake',
    'A Comic Book Cover Of A Superhero Wearing Headphones',
    'A Centered Explosion Of Colorful Powder On A Black Background',
    'A Photo Of A Samoyed Dog With Its Tongue Out Hugging A White Siamese Cat',
    'A Photo Of A White Fur Monster Standing In A Purple Room',
    "A Photo Of Michelangelo's Sculpture Of David Wearing Headphones DJing",
    'A Samurai Riding A Horse On Mars, Lomography',
    'A Modern, Sleek Cadillac Drives Along The Gardiner Expressway With Downtown Toronto In The Background, With A Lens Flare, 50mm Photography',
    'A Realistic Photograph Of A Young Woman With Blue Eyes And Blonde Hair',
    'A Man Standing In Front Of A Stargate To Another Dimension',
    'Spongebob Squarepants In The Blair Witch Project',
    'A Velociraptor Working At A Hotdog Stand, Lomography',
    'A Man Walking Through The Bustling Streets Of Kowloon At Night, Lit By Many Bright Neon Shop Signs, 50mm Lens',
    'A BBQ That Is Alive, In The Style Of A Pixar Animated Movie',
    'A Futuristic Cyborg Dance Club, Neon Lights',
    'The Long-Lost Star Wars 1990 Japanese Anime',
    'A Hamburger In The Shape Of A Rubik’s Cube, Professional Food Photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An Astronaut Encountering An Alien Life Form On A Distant Planet, Photography',
    'A Dinosaur Exploring Cape Town, Photography',
    'A Man Falling In Love With His Computer, Digital Art',
    'A Photograph Of A Cyborg Exploring Tokyo At Night, Lomography',
    'Dracula Walking Down The Street Of New York City In The 1920s, Black And White Photography',
    'Synthwave Aeroplane',
    'A Man Wanders Through The Rainy Streets Of Tokyo, With Bright Neon Signs, 50mm',
    'A Space Shuttle Flying Above Cape Town, Digital Art',

    // 50 additional prompts
    'A Giant Octopus Serving Coffee In A Cozy Cafe, Digital Painting',
    'A Steampunk Owl Wearing Goggles, Perched On A Gear',
    'A Cyberpunk Samurai Battling Robots In A Neon Alley',
    'A Time-Traveling Victorian Lady Riding A Hoverboard',
    'A Polar Bear DJing At An Igloo Rave, Ice Sculptures Everywhere',
    'A Floating Island City Powered By Crystals, Concept Art',
    'A Magical Book That Opens Portals, Surrounded By Glowing Runes',
    'A Dragon Wrapped Around A Skyscraper In A Futuristic City',
    'A Pirate Ship Sailing Through The Clouds',
    'A Cupcake Bakery Run By Penguins, Whimsical Style',
    'A 3D Model Of A Futuristic Train Running Through The Ocean',
    'A Robot Chef Flipping Pancakes In Zero Gravity',
    'A Cat Astronaut Floating Through A Galaxy Of Yarn Balls',
    'A Sorcerer Casting Spells With A Wand Made Of Lightning',
    'A Forest Made Entirely Of Glass Trees, Digital Illustration',
    'A Haunted Mansion With Friendly Ghosts Having A Tea Party',
    'An Alien Marketplace On A Distant Moon, Populated With Creatures',
    'A Jazz Band Made Up Of Dinosaurs Performing On Stage',
    'A Lava Lamp Planet With Gooey Volcanoes',
    'A Garden Gnome Riding A Squirrel Into Battle',
    'A Spaceship Shaped Like A Watermelon In Orbit',
    'A Post-Apocalyptic Landscape With A Rainbow Sky',
    'A Floating Whale City With Lanterns Hanging From Its Fins',
    'A Ballerina Dancing On A Cloud Made Of Cotton Candy',
    'A Mushroom House With Smoke Rings Floating Up The Chimney',
    'A Minotaur Bartender Mixing Potions In A Tavern',
    'A Space Elevator Made Of Laser Beams',
    'A Sunset Over A Planet With Two Suns, Vibrant Colors',
    'A Medieval Knight Texting On A Smartphone, Comedy Art',
    'A 3D Render Of A Giant Panda Flying A Jetpack',
    'A Fairytale Castle Made Of Ice Cream Cones',
    'A Cactus Playing Guitar In A Desert Band',
    'A Mermaid Riding A Dolphin Under Bioluminescent Waves',
    'A Robot Puppy Learning Tricks In A Futuristic Park',
    'A Viking Ship In Space Sailing Through An Asteroid Field',
    'A Time Machine Built From Vintage Radios',
    'A Cute Alien Making Pizza On A Space Station',
    'A Samurai Sloth Balancing On A Cherry Blossom Tree',
    'A Cyber Witch Brewing Potions In A Neon Cauldron',
    'A Tiny Village Built Inside A Giant Teacup',
    'A Monster Truck Shaped Like A Cat Chasing Mice',
    'A Waterfall Pouring Into A Cup Of Tea',
    'A Garden Of Floating Flowers Under A Twilight Sky',
    'A Hedgehog Wearing Sunglasses On A Surfboard',
    'A Floating Library In The Middle Of A Rainbow Storm',
    'A DJ Koala Spinning Vinyl At A Jungle Party',
    'A Map Of A Fantasy World Drawn On A Leaf',
    'A Toy Train Circling A Giant Slice Of Cake',
    'A Campfire Story Told By Talking Fireflies',
    'A Giant Snail Carrying A Village On Its Back',
  ];

  let randomPrompt;
  do {
    randomPrompt = prompts[Math.floor(Math.random() * prompts.length)];
  } while (randomPrompt === currentPrompt);

  return randomPrompt;
};
